### ISSUE TITLE
Manual Refresh for Server Connection and Files

### ISSUE THREAD

**Issue by Xgabi86** [DEVTomatoCake/Pterodactyl-vsc#75]
Introduce the ability to manually refresh server connections and files.

By right-clicking in the file explorer or using a designated command, users can trigger a manual refresh, which will update the server connection and reload the server files.

**Comment by DEVTomatoCake** [comment]
Given that VS Code (at least when using the web version) automatically refreshes when gaining back tab focus, I do not want to add an entry button in the file explorer. Not sure how I could do right clicking.

I've added another command called "Pterodactyl: Refresh server files" which should do the job @Xgabi86.

**Comment by DEVTomatoCake** [comment]
Added in https://github.com/DEVTomatoCake/Pterodactyl-vsc/releases/tag/v1.1.0
